exclude: "_site/"

linters:
  BorderZero:
    enabled: false
  CapitalizationInSelector:
    enabled: true
  ColorKeyword:
    enabled: false
  Comment:
    enabled: false
  Compass::*:
    enabled: false  # Change?
  DebugStatement:
    enabled: true
  DeclarationOrder:
    enabled: true
  DuplicateProperty:
    enabled: true
  EmptyLineBetweenBlocks:
    enabled: true
  EmptyRule:
    enabled: true
  HexLength:
    enabled: true
    style: short
  HexNotation:
    enabled: true
    style: uppercase
  HexValidation:
    enabled: true
  IdWithExtraneousSelector:
    enabled: false
  Indentation:
    enabled: false  # Disabled for extra indentaiton
    width: 4  # Subjective
  LeadingZero:
    enabled: true
  NameFormat:
    enabled: false  # Subjective
  PlaceholderInExtend:
    enabled: true
  PropertySortOrder:
    enabled: false
  PropertySpelling:
    enabled: false
  SelectorDepth:
    enabled: true
  Shorthand:
    enabled: true
  SingleLinePerSelector:
    enabled: true
  SpaceAfterComma:
    enabled: false
  SpaceAfterPropertyColon:
    enabled: true
  SpaceAfterPropertyName:
    enabled: true
  SpaceBeforeBrace:
    enabled: true
  SpaceBetweenParens:
    enabled: true
  StringQuotes:
    enabled: true
    style: double_quotes  # Subjective
  TrailingSemicolonAfterPropertyValue:
    enabled: true
  UrlFormat:
    enabled: true
  UrlQuotes:
    enabled: true
  ZeroUnit:
    enabled: true
